version: '3'

services:
  db:
    image: 'mysql:8'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - 'demo-shop-api-db:/var/lib/mysql'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '3306:3306'

volumes:
  demo-shop-api-db:
